# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/6db39781-9b5b-4eb5-b48d-94058aec190a";
    fsType = "ext4";
  };

  fileSystems."/boot" = { 
    device = "/dev/disk/by-uuid/91F3-9127";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/sdb1";
    fsType = "ext4";
  };

  fileSystems."/mnt/hdd2" = {
    device = "/dev/sda2";
    fsType = "ext4";
  };

  fileSystems."/mnt/nas/research" = {
    device = "airex-nas:/volume1/research";
    fsType = "nfs";
  };

  fileSystems."/mnt/nas/datasets" = {
    device = "airex-nas:/volume1/datasets";
    fsType = "nfs";
  };


  swapDevices = [ { device = "/dev/disk/by-uuid/e0aa367c-e3fb-4213-a675-cbefa54e1b63"; } ];

  networking = {
    interfaces.enp4s0.ipv4.addresses = [{
      address = "10.24.36.39";
      prefixLength = 24;
    }];
    defaultGateway = "10.24.36.1";
    nameservers = [ "10.16.25.13" "10.16.25.15" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
